version: 2

jobs:
  build:
    working_dictionary: ~
    docker:
      - image: cimg/python:3.10.9
    steps:
      - checkout
      - run: python --version
  test:
    working_dictionary: ~
    docker:
      - image: cimg/python:3.10.9
    steps:
      - checkout
      - run: python p1/src/test_HttpRequest_functional.py
      - run: python socket_server/src/test_tcp_udp_server_unit.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build