version: 2

jobs:
  build:
    working_directory: ~
    docker:
      - image: cimg/python:3.10.9
    steps:
      - checkout
      - run: python --version

  test:
    working_directory: ~
    docker:
      - image: cimg/python:3.10.9
    steps:
      - checkout
      - run: python p1/src/test_HttpRequest_functional.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
