version: 2

jobs:
  build:
    working_dictionary: ~
    docker:
      - image: cimg/python:3.10.9
    steps:
      - checkout
      - run: python --version
  test:
    working_dictionary: ~
    docker:
      - image: cimg/python:3.10.9
    steps:
      - checkout
      - run: 
        name: Run Tests
        command: |
        cd p1
        python -m unittest test/test_HttpRequest_functional.py
      #- run: python socket_server/src/test_tcp_udp_server_unit.py
      #- run: python -m p4_ipaddress/src/test_cidr_unit.py
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build